name: phototty
description: "this is phototty"
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  image: ^4.1.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3
  http: ^1.2.0
  uuid: ^4.3.3
  flutter_launcher_icons: ^0.14.4
  google_sign_in: ^6.1.4
  photo_view: ^0.14.0
  cloud_firestore: ^6.1.1
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.5
  flutter_dotenv: ^5.1.0
  photo_manager: ^3.2.0
  google_maps_flutter: 2.14.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  firebase_crashlytics: ^5.0.6

  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.3
  msal_mobile: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
